" Settings
filetype indent plugin on
set autoindent
set expandtab
set ic
set number
set ruler
set shiftwidth=2
set softtabstop=2
set spell spelllang=en_us
set visualbell
syntax on

" Mappings
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap ; ;

" Character Length
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

